# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc2


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
iris = datasets.load_iris() 

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X=iris.data

In [0]:
y=iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn import model_selection

test_size = 0.25
seed = 10
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=test_size, random_state=seed)

In [0]:
y_train

array([2, 2, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 2,
       0, 0, 2, 1, 2, 0, 2, 0, 1, 1, 0, 2, 2, 2, 2, 2, 0, 1, 2, 1, 0, 2,
       1, 1, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 1, 2, 0, 2, 0,
       1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 2, 0, 2, 0, 0, 1, 0, 2, 2, 2, 1, 0,
       2, 0])

In [0]:
y_train.shape

(112,)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
#y_train = y_train.reshape(len(y_train), 1)

In [0]:
#y_test = y_test.reshape(len(y_test), 1)

In [0]:
#from sklearn.preprocessing import OneHotEncoder 
#onehotencoder = OneHotEncoder(sparse = False)
#y_train = onehotencoder.fit_transform(y_train)
#y_test = onehotencoder.fit_transform(y_test)

In [0]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [0]:
y_train.shape

(112, 3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
model.fit(X_train, y_train, 
          validation_data=(X_test, y_test), 
          epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 2s 14ms/sample - loss: 2.6672 - accuracy: 0.3482 - val_loss: 1.8083 - val_accuracy: 0.2895
Epoch 2/100
112/112 [==============================] - 0s 315us/sample - loss: 1.6475 - accuracy: 0.3482 - val_loss: 1.3140 - val_accuracy: 0.1579
Epoch 3/100
112/112 [==============================] - 0s 270us/sample - loss: 1.3436 - accuracy: 0.1071 - val_loss: 1.1794 - val_accuracy: 0.1579
Epoch 4/100
112/112 [==============================] - 0s 341us/sample - loss: 1.2353 - accuracy: 0.0982 - val_loss: 1.1257 - val_accuracy: 0.2632
Epoch 5/100
112/112 [==============================] - 0s 281us/sample - loss: 1.1855 - accuracy: 0.1786 - val_loss: 1.0891 - val_accuracy: 0.2368
Epoch 6/100
112/112 [==============================] - 0s 271us/sample - loss: 1.1545 - accuracy: 0.2143 - val_loss: 1.0559 - val_accuracy: 0.2632
Epoch 7/100
112/112 [==============================] - 0s 280us/sample - l

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
import numpy as np

In [0]:
input_data = np.expand_dims(X_test[0], axis=0)
print(input_data.shape)

(1, 4)


In [0]:
pred = model.predict(input_data)
pred

array([[0.06005713, 0.60954106, 0.33040178]], dtype=float32)

In [0]:
model.predict_classes(X_test)

array([1, 2, 0, 2, 0, 1, 1, 1, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2,
       2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2])

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
y_test[0]

array([0., 1., 0.], dtype=float32)

In [0]:
y_test

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc2


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload
import pandas as pd

In [0]:
prices = pd.read_csv('prices.csv')

In [0]:
prices.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [0]:
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98922 entries, 0 to 98921
Data columns (total 7 columns):
date      98922 non-null object
symbol    98922 non-null object
open      98922 non-null float64
close     98922 non-null float64
low       98922 non-null float64
high      98922 non-null float64
volume    98922 non-null float64
dtypes: float64(5), object(2)
memory usage: 5.3+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
prices = prices.drop(columns = ['date','symbol'])

In [0]:
prices.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
prices.shape

(98922, 5)

In [0]:
data = prices.head(1000)

In [0]:
data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
features = data.drop(columns = 'volume')
label = data['volume']/1000000

In [0]:
features.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [0]:
label.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X = features.to_numpy()

In [0]:
y = label.to_numpy()

In [0]:
type(X)

numpy.ndarray

In [0]:
X = X.astype('float32')
y = y.astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X=tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [149]:
for i in range(100):
    
    w, b = train(X, y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16776
Current Loss on iteration 1 235.09312
Current Loss on iteration 2 234.06105
Current Loss on iteration 3 233.0699
Current Loss on iteration 4 232.11801
Current Loss on iteration 5 231.20383
Current Loss on iteration 6 230.32588
Current Loss on iteration 7 229.48273
Current Loss on iteration 8 228.67296
Current Loss on iteration 9 227.8953
Current Loss on iteration 10 227.14842
Current Loss on iteration 11 226.43114
Current Loss on iteration 12 225.74234
Current Loss on iteration 13 225.08076
Current Loss on iteration 14 224.44542
Current Loss on iteration 15 223.83525
Current Loss on iteration 16 223.24927
Current Loss on iteration 17 222.68645
Current Loss on iteration 18 222.146
Current Loss on iteration 19 221.62692
Current Loss on iteration 20 221.12845
Current Loss on iteration 21 220.64972
Current Loss on iteration 22 220.18996
Current Loss on iteration 23 219.74837
Current Loss on iteration 24 219.32433
Current Loss on iteration 25 218.91707


### Observe values of Weight
- Print the updated values

In [151]:
print('Weights:\n', w.numpy())

Weights:
 [[0.0547828 ]
 [0.0548819 ]
 [0.05422734]
 [0.05533116]]


### Observe values of Bias
- Print the updated values

In [152]:
print('Bias:\n',b.numpy())

Bias:
 [4.607657]
